// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiridxxktahrkxzjfljr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpcmlkeHhrdGFocmt4empmbGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTMzMTQsImV4cCI6MjA3MjIyOTMxNH0.saN_4ZPq2zhdbdi8IFTrRMGaPz8gq-tncMiHI0CyEdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});